Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.define "cicd-vm" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.hostname = "cicd-vm"
    # vm.vm.disk :disk, size: "20GB", primary: true
    vm.vm.network "private_network", ip: "192.168.56.20"
    vm.vm.network "public_network"
    vm.vm.provider "virtualbox" do |vb|
     vb.memory = 4096
     vb.cpus = 2
   end
    vm.vm.provision "shell", path: "provision.sh"
  end
end